export const RecipeData = [
  {
    name: "Japanese Beef Bowl",
    time: 15,
    extra: "Thinly sliced beef (hotpot beef)",
    list: ["Soy Sauce", "Sugar", "Sesame Oil"],
    descList: [
      "Thinly Sliced Beef",
      "1TBS Sesame Oil",
      "1.5-2TBS Sugar",
      "2TBS Soy Sauce",
      "1TBS Water",
      "Onions (optional)",
    ],
    steps: [
      "1. Marinade: Water + Sesame Oil + Sugar + Soy Sauce",
      "2. If marinade is not enough, multiply amount accordingly",
      "3. Slice onions thinly, and sautee in oil until soft (optional)",
      "4. Normally I will unwrap the beef rolls first so it cooks evenly",
      "5. Add sauce to the onions, then add the beef",
      "6. Cook until beef is cooked",
    ],
  },
  {
    name: "Oven Teriyaki Chicken",
    time: 40,
    extra: "Chicken (Thighs)",
    list: ["Soy Sauce", "Garlic", "Sugar", "Rice Wine Vinegar"],
    descList: [
      "2-3 Chicken Thighs",
      "5TBS Sugar",
      "1/4 Cup Water",
      "1/2 Cup Soy Sauce",
      "2TBS Rice Wine Vinegar",
      "Garlic",
    ],
    steps: [
      "1. Slice garlic (Only for marinade, don't need to slice small)",
      "2. Marinade: Mix sugar, water, water, soy sauce, rice wine vinegar, garlic",
      "3. Let chicken marinade in sauce for at least 45 mins",
      "4. Set oven to 350F/ 177C",
      "5. Put chicken on a baking tray and pour marinade over it",
      "6. Bake for 35-40mins",
    ],
  },
  {
    name: "Semur Ayam",
    time: 30,
    extra: "Chicken (Boneless Thighs), Eggs, Potatoes",
    list: ["Kecap Manis", "Garlic", "Shallot"],
    descList: [
      "2-3 Boneless Chicken Thighs",
      "Eggs",
      "Potatoes",
      "Onion",
      "1/2TSP Chicken Powder (optional)",
      "1/4TSP Pepper (optional)",
      "1/2 Onion",
      "2.5TBS Kecap Manis",
      "175ml Water",
    ],
    steps: [
      "1. Hard boil the eggs",
      "2. Chop potatoes, not too big",
      "3. Chop chicken into bite sized",
      "4. Mince garlic, shallot",
      "5. Chop onion, I like long slices",
      "6. Sautee garlic, onion, shallot in oil until onion is slightly soft",
      "7. Add chopped chicken, potatoes, season with chicken powder, pepper",
      "8. Add kecap manis, water into pan and mix",
      "8. Stir constantly, sauce will reduce",
      "9. When sauce is thick and chicken is >=90% cooked, add eggs and baste sauce over it",
    ],
  },
  {
    name: "Asian Garlic Pasta",
    time: 15,
    extra: "Pasta",
    list: ["Sugar", "Garlic", "Soy Sauce", "Oyster Sauce"],
    descList: [
      "Garlic (to taste)",
      "Spring Onion (optional) ",
      "25g Butter",
      "100g Pasta",
      "1TBS Soy Sauce",
      "1~1.5TBS Oyster Sauce",
      "Parmesan (optional)",
      "Chili Flakes (optional)",
    ],
    steps: [
      "1. Boil pasta to al dente",
      "2. Mince garlic, chop spring onions",
      "3. Heat butter in pan",
      "4. Sautee garlic and spring onions until fragrant",
      "5. Add chilli flakes, soy sauce and oyster sauce, cook for 1-2 mins",
      "6. Add pasta and stir for 1-2 mins",
    ],
  },
  {
    name: "Telor Kecap",
    time: 15,
    extra: "Eggs",
    list: ["Kecap Manis", "Soy Sauce"],
    descList: [
      "2 Eggs",
      "1/2TBS Kecap Manis",
      "1/2TBS Soy Sauce",
      "50ml Water",
      "Oil",
      "Garlic (optional)",
      "Spring Onions (optional)",
    ],
    steps: [
      "1. Mix water, soy sauce and oyster sauce in a small bowl",
      "2. Heat up 1TBS oil on the pan",
      "3. Sautee minced garlic and chopped spring onions if you have",
      "4. Crack 2 eggs on the pan",
      "5. Wait for sunny side up eggs to cook 70% done",
      "6. Add sauce mixture on the pan, use a spoon to baste over the egg until fully cooked",
    ],
  },
];
